import {FoodItems} from '../types';

interface Food {
  foodItem: FoodItems;
  point: number;
}

export const foodMap: Array<Food> = [
  {foodItem: 'Apple', point: 15},
  {foodItem: 'Banana', point: 30},
  {foodItem: 'Brocolli', point: 5},
  {foodItem: 'Pizza', point: 40},
  {foodItem: 'Carrot', point: 6},
  {foodItem: 'Grapes', point: 15},
  {foodItem: 'French Fries', point: 30},
  {foodItem: 'Spinach', point: 1},
  {foodItem: 'Hamburger', point: 45},
  {foodItem: 'Ice Cream', point: 25},
  {foodItem: 'Chicken Breast', point: 0},
  {foodItem: 'Sandwich', point: 50},
  {foodItem: 'Watermelon', point: 10},
  {foodItem: 'Egg', point: 1},
  {foodItem: 'Orange', point: 12},
  {foodItem: 'Blueberries', point: 9},
  {foodItem: 'Strawberries', point: 7},
  {foodItem: 'Kiwi', point: 14},
  {foodItem: 'Pineapple', point: 21},
  {foodItem: 'Watermelon', point: 10},
  {foodItem: 'Grapefruit', point: 11},
  {foodItem: 'Cherry', point: 9},
  {foodItem: 'Pear', point: 26},
  {foodItem: 'Peach', point: 9},
  {foodItem: 'Plum', point: 8},
  {foodItem: 'Avocado', point: 9},
  {foodItem: 'Cucumber', point: 3},
  {foodItem: 'Brocolli', point: 4},
  {foodItem: 'Spinach', point: 1},
  {foodItem: 'Cauliflower', point: 5},
  {foodItem: 'Zucchini', point: 3},
  {foodItem: 'Sweet potato', point: 20},
  {foodItem: 'Butternut', point: 16},
  {foodItem: 'Salmon', point: 0},
  {foodItem: 'Tofu', point: 2},
  {foodItem: 'Greek Yoghurt', point: 8},
  {foodItem: 'Cottage Cheese', point: 6},
  {foodItem: 'Almonds', point: 6},
  {foodItem: 'Walnuts', point: 4},
  {foodItem: 'Pasta', point: 25},
  {foodItem: 'Rice Cake', point: 7},
  {foodItem: 'Black Beans', point: 24},
  {foodItem: 'ChickPeas', point: 27},
  {foodItem: 'Lentils', point: 20},
  {foodItem: 'Kidney Beans', point: 24},
  {foodItem: 'Milk', point: 12},
  {foodItem: 'Cheese', point: 1},
  {foodItem: 'Bacon', point: 0},
  {foodItem: 'Beef', point: 0},
];
