export {default as LastSlicedFood} from './last-sliced-food';
export {default as PlayerLifeDisplay} from './player-life-display';
export {default as StartGameButton} from './start-game-button';
export {default as LobbySliceApple} from './lobby-slice-apple';
export {default as ResumeGameButton} from './resume-game-button';
export {default as QuitGameButton} from './quit-game-button';
export {default as FoodSlicer} from './food-slicer';
export {default as Food} from './food';
export {default as CloseGameOverModalButton} from './close-game-over-modal-button';
export * from './basic';
